log_list = [
    'Absolute_Amount_Mean',
    'Absolute_Amount_SDev',
    'AmountNet__NA_Mean',
    'AmountNet__NETZERO_Mean',
    # 'DailyInvoiceCount_Discr',
    # 'Days_Invoice_to_Posting_Date',
    # 'Discount_Amount_Mean',
    # 'Discount_Amount_SDev',
    # 'GF_ReportInvoiceNumRange',
    # 'InvoiceDateSpread',
    # 'ReportIDCounts',
    # 'PostDateSpread',
    'Days_Invoice_to_Clearing_Date_Mean',
    'Days_Invoice_to_Clearing_Date_Min',
    'Days_Invoice_to_Posting_Date_Mean',
    'Days_Invoice_to_Posting_Date_Min',
    'Doc_Num_Spread_Discr_Mean',
    'Gross_Invoice_Amount_Local_Mean',
    'Gross_Invoice_Amount_Local_SDev',
    'Gross_Invoice_Amount_Mean',
    'Gross_Invoice_Amount_SDev',
    'HasFrac_Check_Amount_Mean',
    'Invoice_Number_Length_Mean',
    'Invoice_Number_Length_Discr_Mean',
    'Invoice_Number_AlphasPct_Mean',
    'Max_Abs_Amount_Mean',
    'Min_Abs_Amount_Mean',
    'NotZeroEnding_Check_Amount_Mean',
    'UniqueDigits_Gross_Invoice_Amount_Mean',
    'PaymentDoc_Num_Spread_Discr_Mean',
    'Prop_Check_Number_Count',
    'Prop_Company_Code_Count',
    'Prop_Invoice_Number_Count',
    'Prop_Gross_Invoice_Amount_Count',
    'Prop_Payment_Document_Number_Count',
    'Prop_Vendor_Name_Count',
    'Prop_Vendor_Number_Count',
    'Prop_Whole_Dollar_Count',
]
