max_list = [
    'ProjectID',
    'Report_Group_Flag',
    'ReportID',
    # 'Invoice_Date',
    # 'Voucher_Number',
    # 'Check_Date',
    # 'Posting_Date',
    # 'Clearing_Date',
    # 'Payment_Document_Number',
    # 'Invoice_Number',
    # 'Check_Number',
    'Check_Amount',
    'Invoice_Number_Length',
    'Days_Invoice_to_Check_Date',
    'Days_Invoice_to_Posting_Date',
    'Days_Invoice_to_Void_Date',
    'Days_Invoice_to_Clearing_Date',
    'Invoice_Number_Length_Discr',
    'Invoice_Number_Numeric_Discr',
    'Invoice_Number_AlphasPct_Discr',
    'Invoice_Number_NumsPct_Discr',
    'Invoice_Number_LeadingZeroes_Discr',
    'Daily_Invoice_Count_Discr',
    'Days_Invoice_to_Check_Date_Discr',
    'Days_Invoice_to_Clearing_Date_Discr',
    'Days_Invoice_to_Posting_Date_Discr',
    'Days_Invoice_to_Void_Date_Discr',
    'Gross_Invoice_Amount_Discr',
    'UniqueDigits_Gross_Invoice_Amount_Discr',
    'HasFrac_Gross_Invoice_Amount_Discr',
    'NotZeroEnding_Gross_Invoice_Amount_Discr',
    'Gross_Invoice_Amount_Local_Discr',
    'HasFrac_Gross_Invoice_Amount_Local_Discr',
    'NotZeroEnding_Gross_Invoice_Amount_Local_Discr',
    'Check_Amount_Discr',
    'HasFrac_Check_Amount_Discr',
    'NotZeroEnding_Check_Amount_Discr',
    'Absolute_Amount_Discr',
    'HasFrac_Absolute_Amount_Discr',
    'NotZeroEnding_Absolute_Amount_Discr',
    'Doc_Num_Spread_Discr',
    'PaymentDoc_Num_Spread_Discr',
    'Voucher_Num_Spread_Discr',
    'Void_Indicator__0',
    'Void_Indicator__CLEARED',
    'Void_Indicator__NEGOTIABLE',
    'Void_Indicator__OTH',
    'Void_Indicator__RECONCILED',
    'Void_Indicator__VOIDED',
    'Void_Indicator__NULL',
    'ReportGroup__1',
    'ReportGroup__10',
    'ReportGroup__2',
    'ReportGroup__3',
    'ReportGroup__4',
    'ReportGroup__5',
    'ReportGroup__6',
    'ReportGroup__7',
    'ReportGroup__8',
    'ReportGroup__9',
    'ReportID__10A',
    'ReportID__10B',
    'ReportID__10C',
    'ReportID__10D',
    'ReportID__1A',
    'ReportID__1B',
    'ReportID__1C',
    'ReportID__1D',
    'ReportID__2A',
    'ReportID__2B',
    'ReportID__2C',
    'ReportID__2D',
    'ReportID__3A',
    'ReportID__3B',
    'ReportID__3C',
    'ReportID__3D',
    'ReportID__4A',
    'ReportID__4B',
    'ReportID__4C',
    'ReportID__4D',
    'ReportID__5A',
    'ReportID__5B',
    'ReportID__5C',
    'ReportID__5D',
    'ReportID__6A',
    'ReportID__6B',
    'ReportID__6C',
    'ReportID__6D',
    'ReportID__7A',
    'ReportID__7B',
    'ReportID__7C',
    'ReportID__7D',
    'ReportID__8A',
    'ReportID__8B',
    'ReportID__8C',
    'ReportID__8D',
    'ReportID__9A',
    'ReportID__9B',
    'ReportID__9C',
    'ReportID__9D',
    'Document_Type__0',
    'Document_Type__1',
    'Document_Type__2',
    'Document_Type__APINV',
    'Document_Type__DO',
    'Document_Type__KA',
    'Document_Type__KN',
    'Document_Type__KR',
    'Document_Type__NULL',
    'Document_Type__OTH',
    'Document_Type__RE',
    'Document_Type__RM',
    'Document_Type__RN',
    'Document_Type__XK',
    'Document_Type__YB',
    'Document_Type__YI',
    'Document_Type__YR',
    'Document_Type__YT',
    'Document_Type__Z1',
    'Document_Type__ZF',
    'Document_Type__ZG'
]



